---
services:
  fluentd:
    container_name: fluentd
    image: fluentd_2024:latest
    volumes:
      - ./config:/fluentd/etc
      - ../geoip/config/GeoLite2-City.mmdb:/fluentd/GeoLite2-City.mmdb:ro
    ports:
      - "5140:5140/tcp"
      - "5140:5140/udp"
